 # docker-composeのバージョン
version: "3" 

# コンテナの定義
services:
  # nginxコンテナ
  web:
    # コンテナ名
    container_name: "web"
    # コンテナ作成に使用するDockerfileのパス
    build:
      dockerfile: "./web/Dockerfile"
    # ホストとコンテナのポート番号の対応付け
    # <ホスト側のポート>:<コンテナ側のポート>
    ports:
      - "8080:80"
    # volumeをバインド
    # <ホスト側のパス>:<コンテナ側のパス>
    # srcは後ほど作成するlaravelプロジェクト
    volumes:
      - "../src:/var/www/html"

  # PHPコンテナ
  php:
    # コンテナ名
    container_name: "php"
    # コンテナ作成に使用するDockerfileのパス
    build:
      dockerfile: "./php/Dockerfile"
    # volumeをバインド
    volumes:
      - "../src:/var/www/html"

  # DBコンテナ
  db:
    # コンテナ名
    container_name: "db"
    # コンテナ作成に使用するDockerfileのパス
    build:
      dockerfile: "./db/Dockerfile"
    # ホストとコンテナのポート番号の対応付け
    ports:
      - "3306:3306"
    # 環境変数の指定
    environment:
      - "MYSQL_ROOT_PASSWORD=password"
      - "MYSQL_DATABASE=database"
      - "MYSQL_USER=laravel"
      - "MYSQL_PASSWORD=password"
    # volumeをバインド
    volumes:
      - "./db/data:/var/lib/mysql"